name: pipeline
channels:
  - bioconda
  - conda-forge
dependencies:
  - pandas
  - ete3
  - snakemake-minimal
  - ipykernel
  - fastcluster
  
# to update "conda env update --name pipeline --file environment.yml"