name: pipeline
channels:
  - bioconda
  - conda-forge
dependencies:
  - pandas
  - ete3
  - snakemake-minimal
  - ipykernel
  - fastcluster
  - matplotlib
  - seaborn
  - scikit-learn
  - jinja2
  - biopython
  - panel
  - jupyter_bokeh
  
# to update "conda env update --name pipeline --file environment.yaml"