# download e.g. swiss protein db from: 
# https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
db_file: 'data/alphafold/alphafold.fasta'
# PFAM protein domain database from http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.seed.gz
family_db: 'data/pfam/Pfam-A.seed' 
diamond: './../../diamond-2.0.8/bin/diamond'
raxml: './../../raxml-ng/bin/raxml-ng'
muscle: './../../muscle/muscle3.8.31_i86darwin64'
hmmer: './../../hmmer'
safety: './../safety-windows/main'
mmseqs: "./../../MMseqs2/bin/mmseqs"
# output directory
wrkdir: "out"
datadir: "data"
tempdir: "temp"
# Minimum identity-% to report an alignment
min_identity: '30'  # '10' - '100'
#       id <= 25%    : 'usens' : Ultra sensitive
# 25% < id <= 40%    : 'vsens' : Very sensitive
# 40% < id <= 90%    : 'sens' : Sensitive
# 90% < id           : 'fast' : Fast
# 'auto' : automatically chooses the treshhold based on the sensitivity table above
sensitivity: 'auto'
# multi-step or mcl or mmseqs. multi-step and mcl uses DIAMOND. mmseqs uses MMseqs2.
clustering_algorithm: 'multi-step'
# Clusters smaller/bigger than these limits will not be considered
cluster_min_size: '5'
cluster_max_size: '10000'
# Maximum number of clusters, will be chosen randomly if less than available clusters
cluster_number: '-1'
# Parameter to calculate safety windows. Default: 0.75
alpha_safe: 0.75
# Reference criterion
# "--clustering" - default, depends on clustering: mcl or multi-step
# "--identity" - Highest mean pair-wise identity score
# "--highlow" - Highest lowest pair-wise identity score
# "--similarity" - Highest hmmsearch score (i.e. most similar sequence to the MSA of the cluster)
# "--taxonomy" - Highest node in taxonomic tree, DB should contain taxonomic id as "OX=id"
ref_criterion: '--clustering'

# To output clusters uniformly distributed by their range
uniform: false
bin_size: 1 # How many clusters to draw from each bin.
bin_width: 10 # i.e. '100' will sample '--bin_size'-number of clusters every between sizes 0-99, 100-199, ...