# download e.g. swiss protein db from: 
# https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
db_file: '/wrk/users/gyntartu/pipeline/data/uniprot_sprot.fasta'
# PFAM protein domain database from http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.seed.gz
family_db: '/wrk/users/gyntartu/pipeline/data/pfam/Pfam-A.seed' 
diamond: '/proj/gyntartu/diamond-2.0.8/bin/diamond'
raxml: '/proj/gyntartu/raxml-ng/bin/raxml-ng'
muscle: '/proj/gyntartu/muscle/muscle3.8.31_i86linux64'
hmmer: '/proj/gyntartu/hmmer'
safety: '/proj/gyntartu/alignment-safety/safety-windows/main'
mmseqs: "/proj/gyntartu/MMseqs2/bin/mmseqs"
# output directory
wrkdir: "/wrk/users/gyntartu/pipeline/out"
datadir: "/wrk/users/gyntartu/pipeline/data"
tempdir: "/wrk/users/gyntartu/pipeline/temp"
# Minimum identity-% to report an alignment
min_identity: '90'  # '10' - '100'
# https://github.com/bbuchfink/diamond/wiki/3.-Command-line-options#sensitivity-modes
#       id <= 25%    : --ultra-sensitive
# 25% < id <= 40%    : --very-sensitive
# 40% < id <= 90%    : --sensitive
# 90% < id           : --fast
# 'auto' : automatically chooses the treshhold based on the sensitivity table above
sensitivity: 'auto'
# multi-step or mcl or mmseqs. multi-step and mcl uses DIAMOND. mmseqs uses MMseqs2.
clustering_algorithm: 'multi-step'
# Clusters smaller/bigger than these limits will not be considered
cluster_min_size: '100'
cluster_max_size: '10000'
# Maximum number of clusters, will be chosen randomly if less than available clusters
# set to -1 if you want all clusters
cluster_number: '-1'
# Parameter to calculate safety windows. Default: 0.75
# 0.5 <= a < 1.0
alpha_safe: 0.75
# Reference criterion
# "--clustering" - default, depends on clustering: mcl or multi-step
# "--identity" - Highest mean pair-wise identity score
# "--highlow" - Highest lowest pair-wise identity score
# "--similarity" - Highest hmmsearch score (i.e. most similar sequence to the MSA of the cluster)
# "--taxonomy" - Highest node in taxonomic tree, DB should contain taxonomic id as "OX=id"
ref_criterion: '--taxonomy'